remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Madhumita Majumder]
description: [Data enthusiast with a background in business operations and analytics. Dedicated to solving business problems through data-driven decision-making and impactful visualizations.]
